/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FranchiseManagerRouteImport } from './routes/franchise-manager'
import { Route as FranchiseManagerIndexRouteImport } from './routes/franchise-manager.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FranchiseManagerRoute = FranchiseManagerRouteImport.update({
  id: '/franchise-manager',
  path: '/franchise-manager',
  getParentRoute: () => rootRouteImport,
} as any)
const FranchiseManagerIndexRoute = FranchiseManagerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FranchiseManagerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/franchise-manager': typeof FranchiseManagerRouteWithChildren
  '/franchise-manager/': typeof FranchiseManagerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/franchise-manager': typeof FranchiseManagerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/franchise-manager': typeof FranchiseManagerRouteWithChildren
  '/franchise-manager/': typeof FranchiseManagerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/franchise-manager' | '/franchise-manager/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/franchise-manager'
  id: '__root__' | '/' | '/franchise-manager' | '/franchise-manager/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FranchiseManagerRoute: typeof FranchiseManagerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/franchise-manager': {
      id: '/franchise-manager'
      path: '/franchise-manager'
      fullPath: '/franchise-manager'
      preLoaderRoute: typeof FranchiseManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/franchise-manager/': {
      id: '/franchise-manager/'
      path: '/'
      fullPath: '/franchise-manager/'
      preLoaderRoute: typeof FranchiseManagerIndexRouteImport
      parentRoute: typeof FranchiseManagerRoute
    }
  }
}

interface FranchiseManagerRouteChildren {
  FranchiseManagerIndexRoute: typeof FranchiseManagerIndexRoute
}

const FranchiseManagerRouteChildren: FranchiseManagerRouteChildren = {
  FranchiseManagerIndexRoute: FranchiseManagerIndexRoute,
}

const FranchiseManagerRouteWithChildren =
  FranchiseManagerRoute._addFileChildren(FranchiseManagerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FranchiseManagerRoute: FranchiseManagerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
