/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FranchiseManagerRouteImport } from './routes/franchise-manager'
import { Route as FranchiseManagerIndexRouteImport } from './routes/franchise-manager.index'
import { Route as FranchiseManagerApplicationsRouteImport } from './routes/franchise-manager.applications'
import { Route as FranchiseManagerFranchisesRouteImport } from './routes/franchise-manager.franchises'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FranchiseManagerRoute = FranchiseManagerRouteImport.update({
  id: '/franchise-manager',
  path: '/franchise-manager',
  getParentRoute: () => rootRouteImport,
} as any)
const FranchiseManagerIndexRoute = FranchiseManagerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FranchiseManagerRoute,
} as any)
const FranchiseManagerApplicationsRoute =
  FranchiseManagerApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => FranchiseManagerRoute,
  } as any)
const FranchiseManagerFranchisesRoute =
  FranchiseManagerFranchisesRouteImport.update({
    id: '/franchises',
    path: '/franchises',
    getParentRoute: () => FranchiseManagerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/franchise-manager': typeof FranchiseManagerRouteWithChildren
  '/franchise-manager/applications': typeof FranchiseManagerApplicationsRoute
  '/franchise-manager/franchises': typeof FranchiseManagerFranchisesRoute
  '/franchise-manager/': typeof FranchiseManagerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/franchise-manager/applications': typeof FranchiseManagerApplicationsRoute
  '/franchise-manager/franchises': typeof FranchiseManagerFranchisesRoute
  '/franchise-manager': typeof FranchiseManagerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/franchise-manager': typeof FranchiseManagerRouteWithChildren
  '/franchise-manager/applications': typeof FranchiseManagerApplicationsRoute
  '/franchise-manager/franchises': typeof FranchiseManagerFranchisesRoute
  '/franchise-manager/': typeof FranchiseManagerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/franchise-manager'
    | '/franchise-manager/applications'
    | '/franchise-manager/franchises'
    | '/franchise-manager/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/franchise-manager/applications'
    | '/franchise-manager/franchises'
    | '/franchise-manager'
  id:
    | '__root__'
    | '/'
    | '/franchise-manager'
    | '/franchise-manager/applications'
    | '/franchise-manager/franchises'
    | '/franchise-manager/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FranchiseManagerRoute: typeof FranchiseManagerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/franchise-manager': {
      id: '/franchise-manager'
      path: '/franchise-manager'
      fullPath: '/franchise-manager'
      preLoaderRoute: typeof FranchiseManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/franchise-manager/': {
      id: '/franchise-manager/'
      path: '/'
      fullPath: '/franchise-manager/'
      preLoaderRoute: typeof FranchiseManagerIndexRouteImport
      parentRoute: typeof FranchiseManagerRoute
    }
    '/franchise-manager/applications': {
      id: '/franchise-manager/applications'
      path: '/applications'
      fullPath: '/franchise-manager/applications'
      preLoaderRoute: typeof FranchiseManagerApplicationsRouteImport
      parentRoute: typeof FranchiseManagerRoute
    }
    '/franchise-manager/franchises': {
      id: '/franchise-manager/franchises'
      path: '/franchises'
      fullPath: '/franchise-manager/franchises'
      preLoaderRoute: typeof FranchiseManagerFranchisesRouteImport
      parentRoute: typeof FranchiseManagerRoute
    }
  }
}

interface FranchiseManagerRouteChildren {
  FranchiseManagerApplicationsRoute: typeof FranchiseManagerApplicationsRoute
  FranchiseManagerFranchisesRoute: typeof FranchiseManagerFranchisesRoute
  FranchiseManagerIndexRoute: typeof FranchiseManagerIndexRoute
}

const FranchiseManagerRouteChildren: FranchiseManagerRouteChildren = {
  FranchiseManagerApplicationsRoute: FranchiseManagerApplicationsRoute,
  FranchiseManagerFranchisesRoute: FranchiseManagerFranchisesRoute,
  FranchiseManagerIndexRoute: FranchiseManagerIndexRoute,
}

const FranchiseManagerRouteWithChildren =
  FranchiseManagerRoute._addFileChildren(FranchiseManagerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FranchiseManagerRoute: FranchiseManagerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
